name: hradar2updraft
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - dask
  - pandas
  - scikit-learn
  - pyyaml
  - pytest
  - distributed
  - pip
  - pyproj
  - cartopy
  - tqdm
  - pip:
    - tensorflow
    - tensorflow-probability
    - .
